### ISSUE TITLE
Exceptions aren't caught in request handlers

### ISSUE THREAD

**Issue by chbaker0** [gussmith23/capstats#2]
Because exceptions aren't dealt with in the request handler functions in `capstats_server.cpp`, they exhibit some unexpected behavior. For example, when fetching an invalid user, a '500 Internal Server Error' response is sent rather than a '404 Not Found'.

**Comment by gussmith23** [comment]
acknowledged. request handlers will be rewritten regardless, but I will keep this in mind when rewriting

**Comment by gussmith23** [comment]
oh, nevermind, thanks for the fix

**Comment by chbaker0** [comment]
I'm still adding more exception handlers, if you don't want that I can just stop
